### ISSUE TITLE
Missing HOIP-30.csv file

### ISSUE THREAD

**Issue by prwe98** [jingshenSN2/HOIP_bandgap_prediction#1]
The HOIP-30.csv file is missing, and the entire project cannot run. Can someone provide this file?

**Comment by jingshenSN2** [comment]
Due to a privacy issue, I was not allowed to share the original csv file. Instead, I uploaded HOIP-30_drop.csv, which is a de-duplicated version, feel free to start with it.

**Comment by prwe98** [comment]
> Owner

Thank u
