### ISSUE TITLE
Question about B_feature.csv

### ISSUE THREAD

**Issue by prwe98** [jingshenSN2/HOIP_bandgap_prediction#2]
I want to know what does r_B_s+p / r_B / IE_B / P_B / EA_B / IC_B / VE_B in B_feature mean

**Comment by prwe98** [comment]
> I want to know what does r_B_s+p / r_B / IE_B / P_B / EA_B / IC_B / VE_B in B_feature mean

And what are the units of these numbers?

**Comment by jingshenSN2** [comment]
This repo replicated the work in _Lu S., et al., Nature Comm. 2018, 9, 3405._. You will find the definition of these features in that paper.
